FROM supertokens/supertokens-postgresql:10.1

USER root

COPY --chmod=755 osc-entrypoint.sh /usr/local/bin/osc-entrypoint.sh

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/osc-entrypoint.sh"]
CMD ["/usr/lib/supertokens/jre/bin/java", \
     "-classpath", "/usr/lib/supertokens/core/*:/usr/lib/supertokens/plugin-interface/*:/usr/lib/supertokens/ee/*", \
     "io.supertokens.Main", "/usr/lib/supertokens", "DEV"]
